In [1]:
!pip install pot
!pip install torch
!pip install geomloss
!pip install wget
!pip install mdatagen
!pip install pot
!pip install torch
!pip install geomloss
!pip install wget
!pip install numpy scipy sklearn
!pip install jax
!pip install chex
!pip install attr
!pip install optax



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import torch
import torch.nn as nn
import pandas as pd

from geomloss import SamplesLoss

import ot

import os
import pickle as pkl
import copy

from sklearn.preprocessing import scale
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer

from utils import *
from SoftImpute import softimpute, cv_softimpute
#from DataSetLoader import dataset_loader, ground_truth
from SinkhornImputation import SinkhornImputation
from Sinkhorn_CMI import *
from RR_imputer import RRimputer
import matplotlib.pyplot as plt
#from CMI import *

from Inject_Missing_Values import *

from Miss import *

import argparse
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logging.debug("test")
import pandas as pd

torch.set_default_tensor_type('torch.DoubleTensor')

c:\Users\zhossai3\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\tensor\python_tensor.cpp:434.)
  _C._set_default_tensor_type(t)


In [3]:
import pandas as pd

# Read CSV file into a Pandas DataFrame
groundTruth = pd.read_csv(r'C:\Users\zhossai3\Desktop\My code\OT_Fairness\Data\German Credit\German_Credit_Ground_Truth.csv', delimiter=',', header=0)

# Store feature columns in a DataFrame

X= groundTruth.iloc[:, :-1]  # Selects all rows and all columns except the last one
Y = groundTruth.iloc[:, -1]  # Selects all rows and only the last column

# Display the DataFrames
print(X)  # Print first few rows of features
 # Print first few rows of target variable



     checking-account  duration  credit-history  purpose  credit-amount  \
0                   1         6               0        7           1169   
1                   0        48               1        7           5951   
2                   3        12               0        4           2096   
3                   1        42               1        5           7882   
4                   1        24               2        1           4870   
..                ...       ...             ...      ...            ...   
995                 3        12               1        5           1736   
996                 1        30               1        2           3857   
997                 3        12               1        7            804   
998                 1        45               1        7           1845   
999                 0        45               0        2           4576   

     savings-account  employment-since  installment-rate  other-debtors  \
0                  4    

In [4]:
generator = Inject_Missing_Values()
miss_mcar30,index_mcar30 = generator.MCAR(X,missing_rate=30)
type(miss_mcar30)
miss_mcar30 = pd.concat([miss_mcar30, Y], axis=1)

In [5]:
miss_mcar30_numpy = miss_mcar30.to_numpy()
X_numpy = X.to_numpy()
Y_numpy = Y.to_numpy()

miss_mcar30_tensor = torch.tensor(miss_mcar30_numpy)
groundTruth_tensor = torch.tensor(groundTruth.to_numpy())
X_tensor = torch.tensor(X_numpy)
Y_tensor = torch.tensor(Y_numpy)

In [6]:
bucket_specs = {
     
    11: 4,   # Column 11 → age (4 bins)
    19: 2,  # Column 19 → sex (2 bins)
    21: 2,  # Column 21 → label  (2 bins)
    5: 5,   # Column 5 → savings-account (5 bins)
    15: 4   # Column 15 → jobs (4 bins)
}

# Define multiple attributes for X, Y, Z
X_cols = [11,19]  # Bucketized sensitive attributes (e.g., sex, race, age)
Y_cols = [21]     # Bucketized outcome-related attributes
Z_cols = [5, 15]  

In [ ]:
#sinkhorn
n_mcar30, d_mcar30 = miss_mcar30_tensor.shape
batchsize = 128 # If the batch size is larger than half the dataset's size,
                # it will be redefined in the imputation methods.
lr = 1e-2
epsilon_mcar30 = pick_epsilon(miss_mcar30_tensor)
#epsilon_mcar30 = 0.3
print(epsilon_mcar30)
mask_mcar30= torch.isnan(miss_mcar30_tensor).double()


sk_imputer_mcar30 = SinkhornImputation_CMI(eps=epsilon_mcar30, batchsize=batchsize, lr=lr, niter=2000)
sk_imp_mcar30, sk_maes30mcar, sk_rmses30mcar,cmi_loss = sk_imputer_mcar30.fit_transform(miss_mcar30_tensor, True, 50, groundTruth_tensor, X_cols, Y_cols, Z_cols, bucket_specs)
#using numpy version of data
sk_imp_mcar30_numpy = sk_imp_mcar30.detach().cpu().numpy()

sk_mae_mcar30 = MAE(sk_imp_mcar30,groundTruth_tensor , mask_mcar30)
sk_rmse_mcar30 = RMSE(sk_imp_mcar30, groundTruth_tensor, mask_mcar30)
print(sk_mae_mcar30,sk_rmse_mcar30)

60803.75256962414


INFO:root:Iteration 0:	 Loss: 52654.6970	 Validation MAE: 90.0804	RMSE: 560.0054


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000,

INFO:root:Iteration 50:	 Loss: 3230.5967	 Validation MAE: 90.1026	RMSE: 560.0053


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6338, 1.2676])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6338, 1.2676])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6069, 1.2137])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000,

INFO:root:Iteration 100:	 Loss: 4266.2243	 Validation MAE: 90.1052	RMSE: 560.0063


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6310, 1.2620])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0969,  0.6774,  1.4516,  2.2258,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6310, 1.2620])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0969,  0.6774,  1.4516,  2.2258,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6310, 1.2620])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0969,  0.6774,  1.4516,  2.2258,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 150:	 Loss: 68747.8914	 Validation MAE: 90.1050	RMSE: 560.0075


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6696, 1.3393])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0578,  0.7067,  1.4711,  2.2356,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6696, 1.3393])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0660,  0.7005,  1.4670,  2.2335,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6768, 1.3536])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0660,  0.7005,  1.4670,  2.2335,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 200:	 Loss: 1377.5288	 Validation MAE: 90.1055	RMSE: 560.0062


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6244, 1.2487])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1115,  0.6664,  1.4443,  2.2221,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6213, 1.2425])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1115,  0.6664,  1.4443,  2.2221,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6300, 1.2599])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1115,  0.6664,  1.4443,  2.2221,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 250:	 Loss: 4689.2143	 Validation MAE: 90.1071	RMSE: 560.0063


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6328, 1.2656])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0560,  0.7080,  1.4720,  2.2360,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6328, 1.2656])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0560,  0.7080,  1.4720,  2.2360,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6328, 1.2656])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0560,  0.7080,  1.4720,  2.2360,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 300:	 Loss: 12506.4275	 Validation MAE: 90.1073	RMSE: 560.0070


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6277, 1.2554])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0413,  0.7190,  1.4793,  2.2397,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6277, 1.2554])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0413,  0.7190,  1.4793,  2.2397,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6173, 1.2346])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.0413,  0.7190,  1.4793,  2.2397,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 350:	 Loss: 147789.6290	 Validation MAE: 90.1072	RMSE: 560.0063


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5838, 1.1676])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1149,  0.6639,  1.4426,  2.2213,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5910, 1.1820])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1149,  0.6639,  1.4426,  2.2213,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5910, 1.1820])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1149,  0.6639,  1.4426,  2.2213,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 400:	 Loss: 5953.0064	 Validation MAE: 90.1070	RMSE: 560.0065


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5962, 1.1925])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2052,  0.5961,  1.3974,  2.1987,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5962, 1.1925])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1486,  0.6386,  1.4257,  2.2129,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.5962, 1.1925])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1486,  0.6386,  1.4257,  2.2129,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 450:	 Loss: 821.2131	 Validation MAE: 90.1053	RMSE: 560.0059


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6240, 1.2481])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1533,  0.6351,  1.4234,  2.2117,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6240, 1.2481])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1533,  0.6351,  1.4234,  2.2117,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6240, 1.2481])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1533,  0.6351,  1.4234,  2.2117,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 500:	 Loss: 103662.9413	 Validation MAE: 90.1051	RMSE: 560.0063


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6367, 1.2735])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1825,  0.6131,  1.4088,  2.2044,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6367, 1.2735])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1825,  0.6131,  1.4088,  2.2044,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6367, 1.2735])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1872,  0.6096,  1.4064,  2.2032,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 550:	 Loss: 2157.3318	 Validation MAE: 90.1060	RMSE: 560.0063


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6527, 1.3054])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1670,  0.6247,  1.4165,  2.2082,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6527, 1.3054])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1670,  0.6247,  1.4165,  2.2082,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6527, 1.3054])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1593,  0.6305,  1.4203,  2.2102,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 600:	 Loss: 76696.1425	 Validation MAE: 90.1064	RMSE: 560.0087


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6631, 1.3262])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1507,  0.6370,  1.4246,  2.2123,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6631, 1.3262])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1558,  0.6332,  1.4221,  2.2111,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6631, 1.3262])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1507,  0.6370,  1.4246,  2.2123,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 650:	 Loss: 59036.8905	 Validation MAE: 90.1053	RMSE: 560.0086


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7096, 1.4192])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2042,  0.5968,  1.3979,  2.1989,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7096, 1.4192])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2042,  0.5968,  1.3979,  2.1989,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7096, 1.4192])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2042,  0.5968,  1.3979,  2.1989,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 700:	 Loss: 49409.2182	 Validation MAE: 90.1058	RMSE: 560.0088


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6651, 1.3302])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1956,  0.6033,  1.4022,  2.2011,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6651, 1.3302])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1956,  0.6033,  1.4022,  2.2011,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6651, 1.3302])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.1956,  0.6033,  1.4022,  2.2011,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 750:	 Loss: 31537.2065	 Validation MAE: 90.1056	RMSE: 560.0095


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6879, 1.3758])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2566,  0.5575,  1.3717,  2.1858,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6896, 1.3791])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2566,  0.5575,  1.3717,  2.1858,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6896, 1.3791])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2566,  0.5575,  1.3717,  2.1858,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 800:	 Loss: 53607.6143	 Validation MAE: 90.1050	RMSE: 560.0094


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6950, 1.3901])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4011,  0.4492,  1.2995,  2.1497,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6950, 1.3901])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4011,  0.4492,  1.2995,  2.1497,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6950, 1.3901])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4011,  0.4492,  1.2995,  2.1497,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 850:	 Loss: 4025.4787	 Validation MAE: 90.1047	RMSE: 560.0091


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6647, 1.3295])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3378,  0.4967,  1.3311,  2.1656,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6647, 1.3295])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3378,  0.4967,  1.3311,  2.1656,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6647, 1.3295])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3378,  0.4967,  1.3311,  2.1656,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 900:	 Loss: 32583.0861	 Validation MAE: 90.1043	RMSE: 560.0073


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7055, 1.4110])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3440,  0.4920,  1.3280,  2.1640,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7055, 1.4110])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3663,  0.4753,  1.3169,  2.1584,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7055, 1.4110])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3407,  0.4945,  1.3297,  2.1648,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 950:	 Loss: 7892.4677	 Validation MAE: 90.1045	RMSE: 560.0043


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6556, 1.3112])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4397,  0.4202,  1.2801,  2.1401,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6563, 1.3125])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4397,  0.4202,  1.2801,  2.1401,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6563, 1.3125])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4493,  0.4130,  1.2754,  2.1377,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1000:	 Loss: 84907.3525	 Validation MAE: 90.1050	RMSE: 560.0033


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6501, 1.3001])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4499,  0.4126,  1.2751,  2.1375,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6501, 1.3001])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4629,  0.4028,  1.2686,  2.1343,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6544, 1.3089])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4629,  0.4028,  1.2686,  2.1343,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1050:	 Loss: 57853.5168	 Validation MAE: 90.1057	RMSE: 560.0035


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7199, 1.4398])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5960,  0.3030,  1.2020,  2.1010,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7199, 1.4398])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5871,  0.3097,  1.2064,  2.1032,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7094, 1.4187])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5871,  0.3097,  1.2064,  2.1032,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1100:	 Loss: 15733.9129	 Validation MAE: 90.1063	RMSE: 560.0048


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6471, 1.2943])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6067,  0.2950,  1.1967,  2.0983,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6487, 1.2975])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6067,  0.2950,  1.1967,  2.0983,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6430, 1.2860])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6067,  0.2950,  1.1967,  2.0983,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1150:	 Loss: 485.2307	 Validation MAE: 90.1071	RMSE: 560.0050


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6645, 1.3291])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6160,  0.2880,  1.1920,  2.0960,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6645, 1.3291])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6160,  0.2880,  1.1920,  2.0960,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6645, 1.3291])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6160,  0.2880,  1.1920,  2.0960,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1200:	 Loss: 43469.1121	 Validation MAE: 90.1079	RMSE: 560.0061


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6473, 1.2946])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5525,  0.3356,  1.2237,  2.1119,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6395, 1.2791])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5525,  0.3356,  1.2237,  2.1119,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6401, 1.2801])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5525,  0.3356,  1.2237,  2.1119,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1250:	 Loss: 145299.7062	 Validation MAE: 90.1084	RMSE: 560.0048


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0153,  0.6398,  1.2949])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5533,  0.3350,  1.2233,  2.1117,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0153,  0.6398,  1.2949])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5728,  0.3204,  1.2136,  2.1068,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6332, 1.2664])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5728,  0.3204,  1.2136,  2.1068,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.00

INFO:root:Iteration 1300:	 Loss: 31221.0620	 Validation MAE: 90.1107	RMSE: 560.0041


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0910,  0.5983,  1.2876])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6135,  0.2899,  1.1933,  2.0966,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0910,  0.5983,  1.2876])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6135,  0.2899,  1.1933,  2.0966,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0910,  0.5937,  1.2784])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6135,  0.2899,  1.1933,  2.0966,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1350:	 Loss: 2057.9391	 Validation MAE: 90.1113	RMSE: 560.0042


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6676, 1.3352])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6361,  0.2729,  1.1819,  2.0910,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6676, 1.3352])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6361,  0.2729,  1.1819,  2.0910,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6467, 1.2934])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.6361,  0.2729,  1.1819,  2.0910,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1400:	 Loss: 29935.2236	 Validation MAE: 90.1106	RMSE: 560.0039


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0292,  0.6558,  1.3408])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5903,  0.3073,  1.2049,  2.1024,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0292,  0.6558,  1.3408])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5903,  0.3073,  1.2049,  2.1024,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0394,  0.6507,  1.3408])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5903,  0.3073,  1.2049,  2.1024,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1450:	 Loss: 10008.9952	 Validation MAE: 90.1120	RMSE: 560.0035


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0092,  0.7013,  1.4118])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5140,  0.3645,  1.2430,  2.1215,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0092,  0.7013,  1.4118])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5140,  0.3645,  1.2430,  2.1215,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7059, 1.4118])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.5140,  0.3645,  1.2430,  2.1215,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.00

INFO:root:Iteration 1500:	 Loss: 6817.5920	 Validation MAE: 90.1108	RMSE: 560.0035


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7030, 1.4060])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4293,  0.4280,  1.2853,  2.1427,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7030, 1.4060])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4293,  0.4280,  1.2853,  2.1427,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.7030, 1.4060])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.4293,  0.4280,  1.2853,  2.1427,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

INFO:root:Iteration 1550:	 Loss: 2202.3754	 Validation MAE: 90.1113	RMSE: 560.0022


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0552,  0.6399,  1.3350])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3479,  0.4890,  1.3260,  2.1630,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0552,  0.6399,  1.3350])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3479,  0.4890,  1.3260,  2.1630,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0552,  0.6399,  1.3350])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3479,  0.4890,  1.3260,  2.1630,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1600:	 Loss: 1807.8713	 Validation MAE: 90.1111	RMSE: 560.0022


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1330,  0.6111,  1.3553])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3553,  0.4835,  1.3223,  2.1612,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1252,  0.6150,  1.3553])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3553,  0.4835,  1.3223,  2.1612,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1252,  0.6150,  1.3553])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3553,  0.4835,  1.3223,  2.1612,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1650:	 Loss: 19724.8708	 Validation MAE: 90.1118	RMSE: 560.0017


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0492,  0.6910,  1.4312])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3528,  0.4854,  1.3236,  2.1618,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0492,  0.6910,  1.4312])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3528,  0.4854,  1.3236,  2.1618,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0333,  0.6989,  1.4312])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3528,  0.4854,  1.3236,  2.1618,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1700:	 Loss: 7425.1662	 Validation MAE: 90.1122	RMSE: 560.0022


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0531,  0.6541,  1.3614])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2226,  0.5830,  1.3887,  2.1943,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0531,  0.6569,  1.3669])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2226,  0.5830,  1.3887,  2.1943,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0531,  0.6569,  1.3669])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2465,  0.5652,  1.3768,  2.1884,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1750:	 Loss: 2053.9248	 Validation MAE: 90.1116	RMSE: 560.0038


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1441,  0.5855,  1.3151])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2987,  0.5259,  1.3506,  2.1753,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1441,  0.5855,  1.3151])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2987,  0.5259,  1.3506,  2.1753,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.1424,  0.5864,  1.3151])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3170,  0.5122,  1.3415,  2.1707,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1800:	 Loss: 233800.0304	 Validation MAE: 90.1124	RMSE: 560.0041


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0586,  0.6609,  1.3805])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2523,  0.5608,  1.3739,  2.1869,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0586,  0.6609,  1.3805])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2523,  0.5608,  1.3739,  2.1869,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0586,  0.6526,  1.3638])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2523,  0.5608,  1.3739,  2.1869,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1850:	 Loss: 86615.8531	 Validation MAE: 90.1122	RMSE: 560.0052


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0864,  0.6425,  1.3713])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2214,  0.5839,  1.3893,  2.1946,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0864,  0.6425,  1.3713])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2214,  0.5839,  1.3893,  2.1946,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0864,  0.6425,  1.3713])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2214,  0.5839,  1.3893,  2.1946,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1900:	 Loss: 14057.4460	 Validation MAE: 90.1133	RMSE: 560.0057


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0308,  0.6546,  1.3400])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2147,  0.5889,  1.3926,  2.1963,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0308,  0.6546,  1.3400])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2525,  0.5607,  1.3738,  2.1869,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([-0.0308,  0.6546,  1.3400])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.2525,  0.5607,  1.3738,  2.1869,  3.0000])
tensor([1, 2, 3, 4])
tensor([20

INFO:root:Iteration 1950:	 Loss: 27725.0609	 Validation MAE: 90.1139	RMSE: 560.0055


tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6890, 1.3781])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3450,  0.4913,  1.3275,  2.1638,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6890, 1.3781])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3450,  0.4913,  1.3275,  2.1638,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33.7500, 47.5000, 61.2500, 75.0000])
tensor([1, 2, 3, 4])
tensor([0.0000, 0.6890, 1.3781])
tensor([1, 2])
tensor([0.0000, 0.5000, 1.0000])
tensor([1, 2])
tensor([0.0000, 0.8000, 1.6000, 2.4000, 3.2000, 4.0000])
tensor([1, 2, 3, 4, 5])
tensor([-0.3590,  0.4808,  1.3205,  2.1603,  3.0000])
tensor([1, 2, 3, 4])
tensor([20.0000, 33

TypeError: abs(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [ ]:
fig, ax = plt.subplots(constrained_layout=True)
npoints = len(sk_maes30mcar)

ax.plot(np.linspace(0, 1, npoints) * npoints, sk_maes30mcar, label='Sinkhorn')
ax.set_xticks(np.linspace(0, npoints, 6))
ax.set_xlabel('# Sinkhorn iterations')

#ax.hlines(y=mean_mae_mcar60, xmin=0, xmax=npoints, label="Means", ls = '--', color='black')
#ax.hlines(y=ice_mae_mcar60, xmin=0, xmax=npoints, label="ICE", ls = '--', color='m')
#ax.hlines(y=soft_mae_mcar60, xmin=0, xmax=npoints, label="Softimpute", ls = '--', color='c')

ax.set_ylabel('MAE')
plt.legend()
plt.show()